services:
  - type: web
    name: ielts-mock-platform
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true

