services:
  - type: web
    name: ielts-mock-platform
    runtime: node
    plan: free
    buildCommand: npm install && node prepare-env.js && npx prisma generate && npx prisma db push --accept-data-loss && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
      - key: DATABASE_URL
        value: "file:./dev.db"
      - key: JWT_SECRET
        generateValue: true

